//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC_Healthcare_webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int id { get; set; }
        public int customer_id { get; set; }
        public string product_list { get; set; }
        public decimal total { get; set; }
        public decimal discount { get; set; }
        public decimal final_price { get; set; }
    }
}
