//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC_Healthcare_webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Address
    {
        public int id { get; set; }
        public int customer_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string address_line1 { get; set; }
        public string address_line2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string landmark { get; set; }
        public int pincode { get; set; }
        public string country { get; set; }
        public int mobile_no { get; set; }
        public bool isHome { get; set; }
        public bool isOffice { get; set; }
    }
}
