//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC_Healthcare_webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountOn_category
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Discount_amount { get; set; }
        public bool Active { get; set; }
        public bool isPercentage { get; set; }
        public int min_cart_value { get; set; }
    }
}
