//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC_Healthcare_webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public string Short_description { get; set; }
        public string SKU { get; set; }
        public int Category_id { get; set; }
        public int Quantity { get; set; }
        public decimal MRP { get; set; }
        public decimal Selling_price { get; set; }
        public bool Enabled { get; set; }
        public int Seller_id { get; set; }
    }
}
